sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - composer test

cache:
    directories:
        - $HOME/.composer/cache
